version: "3"
services:
  db:
    image: "postgres:12"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - "54320:5432"
    restart: always
  service:
    image: "sprinbootcore:dev"
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      kafka-serv: kafka:9092

    restart: always
